# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import server.media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessimage',
            name='s3_url',
            field=models.ImageField(blank=True, null=True, upload_to=server.media.models.upload_profile_image_to),
        ),
        migrations.AlterField(
            model_name='image',
            name='s3_url',
            field=models.ImageField(blank=True, null=True, upload_to=server.media.models.upload_profile_image_to),
        ),
    ]
