# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import server.media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20170708_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessimage',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='businessimage',
            name='s3_url',
            field=models.ImageField(blank=True, default='', upload_to=server.media.models.upload_profile_image_to),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='s3_url',
            field=models.ImageField(blank=True, default='', upload_to=server.media.models.upload_profile_image_to),
        ),
    ]
