# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20170609_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessimage',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Created At'),
        ),
    ]
