# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20170712_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessimage',
            name='type',
            field=models.CharField(max_length=12),
        ),
    ]
