# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20170609_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessimage',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='businessimage',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business'),
        ),
    ]
