# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20170712_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessimage',
            name='ref',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
