# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('taxid', models.CharField(max_length=15)),
                ('zip', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=40)),
                ('address2', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=25)),
                ('facebook_link', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=50, null=True)),
                ('managed_account_token', models.CharField(blank=True, max_length=50, null=True)),
                ('security_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('ssn_token', models.CharField(blank=True, max_length=10, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessBillingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=0)),
                ('type', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=4)),
                ('token', models.CharField(max_length=70)),
                ('zip', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=40)),
                ('address2', models.CharField(max_length=40)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.State')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Category')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Category'),
        ),
        migrations.AddField(
            model_name='business',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country'),
        ),
        migrations.AddField(
            model_name='business',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.State'),
        ),
        migrations.AddField(
            model_name='business',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.SubCategory'),
        ),
    ]
