# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesssocial',
            name='business',
        ),
        migrations.AddField(
            model_name='business',
            name='facebook_link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='instagram_link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='linkedin_link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='twitter_link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='BusinessSocial',
        ),
    ]
