# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='security_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='ssn_token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
