# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='managed_account_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businessbillinginfo',
            name='token',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
