# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20170512_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessbillinginfo',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.Business'),
        ),
    ]
