# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20170519_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
