# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
    ]
