# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import server.business.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20170714_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='picture1',
            field=models.ImageField(upload_to=server.business.models.upload_profile_image_to),
            preserve_default=False,
        ),
    ]
