# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business_managed_account_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country'),
        ),
        migrations.AlterField(
            model_name='business',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.State'),
        ),
    ]
