# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20170512_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
