# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_business_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='managed_account_token',
            new_name='customer_token',
        ),
    ]
