# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20170718_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='hours',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
