# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20170721_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='hours',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
