# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20170721_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.SubCategory'),
        ),
    ]
