# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1)),
                ('profile_photo_url', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('payment_method', models.CharField(max_length=10)),
                ('payment_text', models.CharField(max_length=5)),
                ('payment_token', models.CharField(max_length=70)),
                ('dob', models.DateField()),
                ('last_geo_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_geo_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('tos_accept_date', models.DateTimeField(verbose_name='Terms of Service Accept Date')),
                ('tos_accept_version', models.CharField(max_length=15)),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
        ),
    ]
