# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_accountroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPartnerRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=25)),
                ('role_description', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='accountroles',
            name='account',
        ),
        migrations.DeleteModel(
            name='AccountRoles',
        ),
    ]
