# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('account', '0003_auto_20170705_0408'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('posted', models.BooleanField(default=0)),
                ('business_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('business_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('business_amount_processed', models.BooleanField(default=0)),
                ('business_amount_processed_date', models.DateTimeField(blank=True, null=True, verbose_name='Business Amount Processed Date')),
                ('member_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('member_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('member_amount_processed', models.BooleanField(default=0)),
                ('member_amount_processed_date', models.DateTimeField(blank=True, null=True, verbose_name='Member Amount Processed Date')),
                ('member_ref_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('member_ref_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('member_ref_amount_processed', models.BooleanField(default=0)),
                ('member_ref_amount_processed_date', models.DateTimeField(blank=True, null=True, verbose_name='Member Referral Amount Processed Date')),
                ('void_date', models.DateTimeField(auto_now=True, verbose_name='Void Date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_member', to='account.Account')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
                ('cashier_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
                ('member_referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_member_referral', to='member.Member')),
            ],
        ),
    ]
