# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('business', '0003_auto_20170522_1739'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('posted', models.BooleanField(default=0)),
                ('business_percent', models.DecimalField(decimal_places=2, max_digits=9)),
                ('business_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('business_amount_processed', models.BooleanField()),
                ('business_amount_processed_date', models.DateTimeField(verbose_name='Business Amount Processed Date')),
                ('member_percent', models.DecimalField(decimal_places=2, max_digits=9)),
                ('member_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('member_amount_processed', models.BooleanField()),
                ('member_amount_processed_date', models.DateTimeField(verbose_name='Member Amount Processed Date')),
                ('member_ref_percent', models.DecimalField(decimal_places=2, max_digits=9)),
                ('member_ref_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('member_ref_amount_processed', models.BooleanField()),
                ('member_ref_amount_processed_date', models.DateTimeField(verbose_name='Member Referral Amount Processed Date')),
                ('void_date', models.DateTimeField(verbose_name='Void Date')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
