# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='business_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='business_amount_processed_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Business Amount Processed Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='business_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member_amount_processed_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Member Amount Processed Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member_ref_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member_ref_amount_processed_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Member Referral Amount Processed Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member_ref_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member_referral',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_member_referral', to='member.Member'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='void_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Void Date'),
        ),
    ]
