# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('purchase', '0002_auto_20170522_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='member_referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_referral', to='member.Member'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='member.Member'),
        ),
    ]
