# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20170710_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='business_amount_processed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Business Amount Processed Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member_amount_processed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Member Amount Processed Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member_ref_amount_processed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Member Referral Amount Processed Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='void_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Void Date'),
        ),
    ]
