# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-24 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20170818_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='member_referral',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_member_referral', to='member.Member'),
        ),
    ]
