# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20170522_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='business_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='business_amount_processed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Business Amount Processed Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='business_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member_amount_processed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Member Amount Processed Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member_ref_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member_ref_amount_processed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Member Referral Amount Processed Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member_ref_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member_referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_referral', to='member.Member'),
        ),
    ]
