# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20170522_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='business_amount_processed',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member_amount_processed',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='member_ref_amount_processed',
            field=models.BooleanField(default=0),
        ),
    ]
