# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_auto_20170714_0319'),
        ('business', '0004_auto_20170716_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.CharField(blank=True, max_length=100, null=True)),
                ('approved', models.BooleanField(default=0)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('account', 'business')]),
        ),
    ]
