# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
