# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_code', models.CharField(max_length=5)),
                ('abbrev', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=4)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('profile_photo_url', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('mailing_address_1', models.CharField(max_length=40)),
                ('mailing_address_2', models.CharField(max_length=40)),
                ('mailing_address_city', models.CharField(max_length=50)),
                ('mailing_address_zip', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=10)),
                ('payment_text', models.CharField(max_length=5)),
                ('payment_token', models.CharField(max_length=70)),
                ('security_hash', models.CharField(max_length=32)),
                ('birthdate', models.DateTimeField(verbose_name='birth date')),
                ('ssn_token', models.CharField(max_length=10)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Language')),
                ('mailing_address_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('profile_photo_url', models.CharField(max_length=100)),
                ('email1', models.CharField(max_length=100)),
                ('email2', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('mailing_address_1', models.CharField(max_length=40)),
                ('mailing_address_2', models.CharField(max_length=40)),
                ('mailing_address_city', models.CharField(max_length=50)),
                ('mailing_address_zip', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=10)),
                ('payment_token', models.CharField(max_length=70)),
                ('security_hash', models.CharField(max_length=32)),
                ('birthdate', models.DateTimeField(verbose_name='birth date')),
                ('ssn_token', models.CharField(max_length=10)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Language')),
                ('mailing_address_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Country')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Language')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='mailing_address_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.State'),
        ),
        migrations.AddField(
            model_name='member',
            name='mailing_address_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.State'),
        ),
        migrations.AddField(
            model_name='country',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Language'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Question'),
        ),
    ]
