# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
