# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_photo_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
