# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='partner_role',
            new_name='partner_roles',
        ),
    ]
