# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170509_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPartnerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=25)),
                ('role_description', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountpartnerroles', to='account.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='accountpartnerroles',
            name='account',
        ),
        migrations.DeleteModel(
            name='AccountPartnerRoles',
        ),
    ]
