# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import server.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170530_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_photo_url',
            field=models.ImageField(blank=True, null=True, upload_to=server.account.models.upload_profile_image_to),
        ),
    ]
