# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import server.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170705_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_photo_url',
            field=models.ImageField(blank=True, default='', upload_to=server.account.models.upload_profile_image_to),
        ),
        migrations.AlterField(
            model_name='account',
            name='referral_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_referral', to='member.Member'),
        ),
        migrations.AlterField(
            model_name='accountpartnerrole',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
