# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170705_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_email_or_phone', models.CharField(max_length=40)),
                ('friend_ip', models.CharField(blank=True, max_length=15, null=True)),
                ('friend_user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('friend_referrer', models.CharField(blank=True, max_length=200, null=True)),
                ('connected', models.BooleanField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='referral_member',
        ),
        migrations.AddField(
            model_name='account',
            name='referral_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_referral', to='account.Account'),
        ),
        migrations.AddField(
            model_name='accountreferral',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
