# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170609_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPartnerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='accountrole',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accountrole',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='account',
            name='roles',
        ),
        migrations.DeleteModel(
            name='AccountRole',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='accountpartnerrole',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
