# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170708_2038'),
        ('account', '0004_auto_20170710_0052'),
    ]

    operations = [
    ]
