# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import server.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170710_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_photo_url',
            field=models.ImageField(upload_to=server.account.models.upload_profile_image_to),
            preserve_default=False,
        ),
    ]
