# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_description'),
        ('account', '0005_auto_20170614_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpartnerrole',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business'),
            preserve_default=False,
        ),
    ]
