# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170714_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
