# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='verified',
        ),
        migrations.AddField(
            model_name='account',
            name='email_verified',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_verified',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
