# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170708_1846'),
        ('account', '0009_auto_20170724_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Country'),
        ),
    ]
