# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_account_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='new_email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='new_email_verified',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='new_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='new_phone_verified',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
