# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20170731_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(default='', max_length=25),
        ),
    ]
