# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20170818_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountreferral',
            name='friend_ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
