# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('category', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=1000)),
                ('state', models.BooleanField(default=0)),
            ],
        ),
    ]
