# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('account', '0003_auto_20170705_0408'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='account',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='end',
            field=models.DateTimeField(blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='notification',
            name='start',
            field=models.DateTimeField(blank=True),
            preserve_default=False,
        ),
    ]
