# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20170707_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
