# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20170714_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
