# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20170717_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Create Date'),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
    ]
