# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('account', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_address_1', models.CharField(max_length=40)),
                ('mailing_address_2', models.CharField(max_length=40)),
                ('mailing_address_city', models.CharField(max_length=50)),
                ('mailing_address_zip', models.CharField(max_length=20)),
                ('security_hash', models.CharField(max_length=32)),
                ('ssn_token', models.CharField(max_length=10)),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
                ('mailing_address_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country')),
                ('mailing_address_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.State')),
                ('profile_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Image')),
            ],
        ),
        migrations.CreateModel(
            name='MemberPaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=5)),
                ('token', models.CharField(max_length=70)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
    ]
