# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mailing_address_2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
