# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Image'),
        ),
        migrations.AlterField(
            model_name='member',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
