# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170517_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='customer_token',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
    ]
