# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170523_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='security_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='ssn_token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
