# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170706_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberreferral',
            name='member',
        ),
        migrations.DeleteModel(
            name='MemberReferral',
        ),
    ]
