# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_customer_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='customer_token',
            new_name='managed_account_token',
        ),
    ]
