# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20170530_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_email_or_phone', models.CharField(max_length=40)),
                ('friend_ip', models.CharField(max_length=15)),
                ('friend_user_agent', models.CharField(max_length=20)),
                ('friend_referrer', models.CharField(max_length=30)),
                ('connected', models.BooleanField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
    ]
