# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20170710_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ssn_token',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='memberpaymentinfo',
            name='text',
            field=models.CharField(max_length=15),
        ),
    ]
