# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_memberreferral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberreferral',
            name='friend_ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='memberreferral',
            name='friend_referrer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memberreferral',
            name='friend_user_agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
