# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20170529_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpaymentinfo',
            name='routing_number',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberpaymentinfo',
            name='text',
            field=models.CharField(max_length=4),
        ),
    ]
