# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20170711_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberpaymentinfo',
            name='type',
        ),
    ]
